[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "nd-tool"
version = "1.0.1"
description = "A simple terminal script to diagnose network issues. Checks for connection problems, poor speeds, and basic security risks using standard Python."
authors = [
  { name = "Terabase Studios", email = "terabasestudios@gmail.com" }
]

readme = { file = "README.md", content-type = "text/markdown" }
license = { file = "LICENSE" }
requires-python = ">=3.8"
keywords = ["network", "diagnostics", "cli", "LAN", "networking"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Topic :: System :: Networking",
    "Topic :: Utilities"
]

dependencies = []

[project.scripts]
nd = "nd_tool.main:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["nd_tool*"]

[project.urls]
Homepage = "https://github.com/Terabase-Studios/network-diagnostics"
Repository = "https://github.com/Terabase-Studios/network-diagnostics"
Issues = "https://github.com/Terabase-Studios/network-diagnostics/issues"
#Documentation = "https://github.com/Terabase-Studios/network-diagnostics/wiki"